### ISSUE TITLE
Adding the project to the official `implementations` page 

### ISSUE THREAD

**Issue by LamprosPitsillos** [616b2f/bsp.nvim#1]
https://github.com/build-server-protocol/build-server-protocol/blob/master/website/generated/docs/overview/implementations.md

I was thinking of adding it my self , but though of asking for your permission first

**Comment by 616b2f** [comment]
Thanks for asking first. I'm fine if you put it there, but maybe with an info that's currently in pre alpha state, so that people don't have the wrong assumption.

**Comment by 616b2f** [comment]
As you already proposed this in the official repo, I will close this issue here. Thank you
