### ISSUE TITLE
Cannot create configs

### ISSUE THREAD

**Issue by dphaldes** [616b2f/bsp.nvim#2]
I have installed the bsp jar (I used a local mason repo using the same yaml file instead of your fork because of some parsing errors) and Mason loads/installs it fine. This plugin also loads correctly, but I am unable to create the config for `gradle-bsp`. The command does nothing, with no output. 

I am aware that this plugin is early in development and I would love to help you out. I am trying to get some meaningful data from  `buildTarget/dependencyModules` and `buildTarget/dependencySources` so that I can pipe them to plugins like neotree.

**Comment by 616b2f** [comment]
Hi,

> I have installed the bsp jar (I used a local mason repo using the same yaml file instead of your fork because of some parsing errors) and Mason loads/installs it fine. 

I will change the Readme to avoid that confusion, you are actually right it does not work with "github:616b2f/mason-repository", I got the same error after I tried it for myself, as used the same method you described when I developed and just thought changing from "file" to "github" reference would work the same, but it does not. Thank you for pointing that out!

> This plugin also loads correctly, but I am unable to create the config for gradle-bsp. The command does nothing, with no output.

You have to run `:BspCreateConfig gradle-bsp`, did you run it without specifying the server name?

**Comment by 616b2f** [comment]
I added a hint if `BspCreateConfig` command is called without a parameter, just in case :)

**Comment by dphaldes** [comment]
Yeah, I am using the correct syntax `BspCreateConfig gradle-bsp`. There is no change after running the command. No new files created or error messages.

**Comment by 616b2f** [comment]
I am currently have no clue why it's not working on your site, I added some more error handling and notifications. Maybe you can try again and report back.

Also I only tested it on Linux, it may have issues on Windows or MacOS.

**Comment by dphaldes** [comment]
The logging helped! The problem was autocomplete. The command I was trying to run was `:BspCreateConfig gradle-bsp ` (with the trailing space) and thus it failed. The command should probably be trimmed to eliminate spaces and this issue can be marked as fixed :)

**Comment by dphaldes** [comment]
On an unrelated note, does this plugin rely on jdtls/lspconfig by any chance ? I get this error when trying to load bsp, 
> Spawning language server with cmd: `java` failed with error message: attempt to call a nil value

~~It could be trying to run `gradle` command which is not installed on my system. Java/Gradle uses project specific gradle binaries through a `gradlew` script present in the root of workspace. It would be nice if the plugin could accommodate that.~~
Apparently, it tries to run `java` directly. I am not sure why that fails as java works fine on my system

**Comment by 616b2f** [comment]
> The logging helped! The problem was autocomplete. The command I was trying to run was `:BspCreateConfig gradle-bsp ` (with the trailing space) and thus it failed. The command should probably be trimmed to eliminate spaces and this issue can be marked as fixed :)

sounds as a good idea, would you like to create an PR for that?

**Comment by 616b2f** [comment]
> On an unrelated note, does this plugin rely on jdtls/lspconfig by any chance ? I get this error when trying to load bsp,
> 
> > Spawning language server with cmd: `java` failed with error message: attempt to call a nil value
> 
> ~It could be trying to run `gradle` command which is not installed on my system. Java/Gradle uses project specific gradle binaries through a `gradlew` script present in the root of workspace. It would be nice if the plugin could accommodate that.~ Apparently, it tries to run `java` directly. I am not sure why that fails as java works fine on my system

no it does not rely on any of those, you see "language server" in your error message only because I copied the RPC part from Neovim, from the LSP implementation. I made the error messages more generic, so that they don't mislead.

What you can try to narrow down the issue, try copy the `argv` part from your `.bsp/gradle-bsp.json`, this is the command that actually should be run and try to run it in your terminal, from the root of your repository.

**Comment by dphaldes** [comment]
Yes. I realized that after I read through the json file. I will experiment and figure out what exactly is the problem on my end. Just a general suggestion, it would be nicer if the entry was called "command" instead of "argv"

**Comment by 616b2f** [comment]
> Yes. I realized that after I read through the json file. I will experiment and figure out what exactly is the problem on my end. Just a general suggestion, it would be nicer if the entry was called "command" instead of "argv"

OK feel free to open a new issue if you find something that can be improved. 

Regarding "argv" the file schema is part of the BSP specification.
